# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import photo_of_day_pb2 as photo__of__day__pb2


class PhotoOfDayServiceStub(object):
    """Service pour gérer les statistiques des photos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IncrementReaction = channel.unary_unary(
                '/photoofday.PhotoOfDayService/IncrementReaction',
                request_serializer=photo__of__day__pb2.IncrementReactionRequest.SerializeToString,
                response_deserializer=photo__of__day__pb2.IncrementReactionResponse.FromString,
                )
        self.GetPhotoOfDay = channel.unary_unary(
                '/photoofday.PhotoOfDayService/GetPhotoOfDay',
                request_serializer=photo__of__day__pb2.GetPhotoOfDayRequest.SerializeToString,
                response_deserializer=photo__of__day__pb2.GetPhotoOfDayResponse.FromString,
                )
        self.GetPhotoStats = channel.unary_unary(
                '/photoofday.PhotoOfDayService/GetPhotoStats',
                request_serializer=photo__of__day__pb2.GetPhotoStatsRequest.SerializeToString,
                response_deserializer=photo__of__day__pb2.GetPhotoStatsResponse.FromString,
                )


class PhotoOfDayServiceServicer(object):
    """Service pour gérer les statistiques des photos
    """

    def IncrementReaction(self, request, context):
        """Incrémente le compteur de réactions pour une photo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPhotoOfDay(self, request, context):
        """Récupère la photo du jour (la plus populaire)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPhotoStats(self, request, context):
        """Récupère les statistiques d'une photo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhotoOfDayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IncrementReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementReaction,
                    request_deserializer=photo__of__day__pb2.IncrementReactionRequest.FromString,
                    response_serializer=photo__of__day__pb2.IncrementReactionResponse.SerializeToString,
            ),
            'GetPhotoOfDay': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPhotoOfDay,
                    request_deserializer=photo__of__day__pb2.GetPhotoOfDayRequest.FromString,
                    response_serializer=photo__of__day__pb2.GetPhotoOfDayResponse.SerializeToString,
            ),
            'GetPhotoStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPhotoStats,
                    request_deserializer=photo__of__day__pb2.GetPhotoStatsRequest.FromString,
                    response_serializer=photo__of__day__pb2.GetPhotoStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photoofday.PhotoOfDayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PhotoOfDayService(object):
    """Service pour gérer les statistiques des photos
    """

    @staticmethod
    def IncrementReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/photoofday.PhotoOfDayService/IncrementReaction',
            photo__of__day__pb2.IncrementReactionRequest.SerializeToString,
            photo__of__day__pb2.IncrementReactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPhotoOfDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/photoofday.PhotoOfDayService/GetPhotoOfDay',
            photo__of__day__pb2.GetPhotoOfDayRequest.SerializeToString,
            photo__of__day__pb2.GetPhotoOfDayResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPhotoStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/photoofday.PhotoOfDayService/GetPhotoStats',
            photo__of__day__pb2.GetPhotoStatsRequest.SerializeToString,
            photo__of__day__pb2.GetPhotoStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
