apiVersion: v1
kind: Service
metadata:
  name: photo-service
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: photo-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      containers:
        - name: photo-service
          image: gitlab-df-registry.imt-atlantique.fr/devops/devops-s26-07/photo:latest
          env:
          - name: LOG_LEVEL
            value: DEBUG
          - name: MONGO_HOST
            value: mongodb
          - name: TAGS_HOST
            value: tags-service
          - name: PHOTOGRAPHER_HOST
            value: photographer-service
          imagePullPolicy: Always
          resources:
           limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: regcred
