# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tags.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntags.proto\x12\x04tags\"\x1c\n\x0cImageRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\"\x19\n\tTagsReply\x12\x0c\n\x04tags\x18\x01 \x03(\t28\n\x04Tags\x12\x30\n\x07GetTags\x12\x12.tags.ImageRequest\x1a\x0f.tags.TagsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tags_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=20
  _globals['_IMAGEREQUEST']._serialized_end=48
  _globals['_TAGSREPLY']._serialized_start=50
  _globals['_TAGSREPLY']._serialized_end=75
  _globals['_TAGS']._serialized_start=77
  _globals['_TAGS']._serialized_end=133
# @@protoc_insertion_point(module_scope)
