# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photo_of_day.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photo_of_day.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12photo_of_day.proto\x12\nphotoofday\"Y\n\x18IncrementReactionRequest\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x10\n\x08photo_id\x18\x02 \x01(\x05\x12\x15\n\rreaction_type\x18\x03 \x01(\t\"V\n\x19IncrementReactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0ftotal_reactions\x18\x03 \x01(\x05\"<\n\x14GetPhotoOfDayRequest\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\"\x8a\x02\n\x15GetPhotoOfDayResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x10\n\x08photo_id\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_reactions\x18\x04 \x01(\x05\x12T\n\x12reaction_breakdown\x18\x05 \x03(\x0b\x32\x38.photoofday.GetPhotoOfDayResponse.ReactionBreakdownEntry\x12\x11\n\tphoto_url\x18\x06 \x01(\t\x1a\x38\n\x16ReactionBreakdownEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\">\n\x14GetPhotoStatsRequest\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\x12\x10\n\x08photo_id\x18\x02 \x01(\x05\"\xb0\x02\n\x15GetPhotoStatsResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x10\n\x08photo_id\x18\x03 \x01(\x05\x12\x17\n\x0ftotal_reactions\x18\x04 \x01(\x05\x12T\n\x12reaction_breakdown\x18\x05 \x03(\x0b\x32\x38.photoofday.GetPhotoStatsResponse.ReactionBreakdownEntry\x12\x1b\n\x13\x66irst_reaction_date\x18\x06 \x01(\t\x12\x1a\n\x12last_reaction_date\x18\x07 \x01(\t\x1a\x38\n\x16ReactionBreakdownEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\xa1\x02\n\x11PhotoOfDayService\x12`\n\x11IncrementReaction\x12$.photoofday.IncrementReactionRequest\x1a%.photoofday.IncrementReactionResponse\x12T\n\rGetPhotoOfDay\x12 .photoofday.GetPhotoOfDayRequest\x1a!.photoofday.GetPhotoOfDayResponse\x12T\n\rGetPhotoStats\x12 .photoofday.GetPhotoStatsRequest\x1a!.photoofday.GetPhotoStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photo_of_day_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPHOTOOFDAYRESPONSE_REACTIONBREAKDOWNENTRY']._loaded_options = None
  _globals['_GETPHOTOOFDAYRESPONSE_REACTIONBREAKDOWNENTRY']._serialized_options = b'8\001'
  _globals['_GETPHOTOSTATSRESPONSE_REACTIONBREAKDOWNENTRY']._loaded_options = None
  _globals['_GETPHOTOSTATSRESPONSE_REACTIONBREAKDOWNENTRY']._serialized_options = b'8\001'
  _globals['_INCREMENTREACTIONREQUEST']._serialized_start=34
  _globals['_INCREMENTREACTIONREQUEST']._serialized_end=123
  _globals['_INCREMENTREACTIONRESPONSE']._serialized_start=125
  _globals['_INCREMENTREACTIONRESPONSE']._serialized_end=211
  _globals['_GETPHOTOOFDAYREQUEST']._serialized_start=213
  _globals['_GETPHOTOOFDAYREQUEST']._serialized_end=273
  _globals['_GETPHOTOOFDAYRESPONSE']._serialized_start=276
  _globals['_GETPHOTOOFDAYRESPONSE']._serialized_end=542
  _globals['_GETPHOTOOFDAYRESPONSE_REACTIONBREAKDOWNENTRY']._serialized_start=486
  _globals['_GETPHOTOOFDAYRESPONSE_REACTIONBREAKDOWNENTRY']._serialized_end=542
  _globals['_GETPHOTOSTATSREQUEST']._serialized_start=544
  _globals['_GETPHOTOSTATSREQUEST']._serialized_end=606
  _globals['_GETPHOTOSTATSRESPONSE']._serialized_start=609
  _globals['_GETPHOTOSTATSRESPONSE']._serialized_end=913
  _globals['_GETPHOTOSTATSRESPONSE_REACTIONBREAKDOWNENTRY']._serialized_start=486
  _globals['_GETPHOTOSTATSRESPONSE_REACTIONBREAKDOWNENTRY']._serialized_end=542
  _globals['_PHOTOOFDAYSERVICE']._serialized_start=916
  _globals['_PHOTOOFDAYSERVICE']._serialized_end=1205
# @@protoc_insertion_point(module_scope)
